import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container ${inter.variable} font-sans`}>
        <section className="grid min-h-screen place-content-center gap-4 text-center lg:gap-8">
          <h1 className="mx-auto max-w-3xl text-5xl font-bold tracking-tight text-gray-900 lg:text-6xl">
            Double the hires, half the effort
          </h1>
          <p className="mx-auto max-w-prose text-gray-600 lg:text-lg">
            Open conversations and nurture relationships at scale and be the first choice when your
            ideal candidate is ready to explore.
          </p>
          <button className="mx-auto max-w-max rounded-md bg-gray-200 px-4 py-2 text-sm font-semibold text-gray-900 transition-colors active:bg-gray-300 lg:text-base">
            View Kula Outreach
          </button>
        </section>
        <section className="grid min-h-screen place-content-center gap-4 text-center lg:gap-8">
          <h1 className="mx-auto max-w-3xl text-5xl font-bold tracking-tight text-gray-900 lg:text-6xl">
            Turn employee's networks into your talent pipeline
          </h1>
          <p className="mx-auto max-w-prose text-gray-600 lg:text-lg">
            Bring all professional connections of your existing team members on one platform,
            request referrals in a click, and get an intro in another.
          </p>
          <button className="mx-auto max-w-max rounded-md bg-gray-200 px-4 py-2 text-sm font-semibold text-gray-900 transition-colors active:bg-gray-300 lg:text-base">
            View Circles
          </button>
        </section>
      </main>
    </>
  );
}
